const collections = [
  { id: 'product', title: '产品与工作', description: '工作中的思考、计划与复盘', color: 'coral', updated: '今天 09:42', notes: [
    { id: 'product-1', title: '关于个人知识管理的一些思考', content: '# 关于个人知识管理的一些思考\n\n信息不等于知识，知识也不等于智慧。\n\n## 我的三个原则\n\n- 让记录足够简单\n- 让回顾成为习惯\n- 让想法彼此连接', favorite: true },
    { id: 'product-2', title: '2025 年第二季度目标', content: '# 2025 年第二季度目标\n\n> 少做一点，但做深。\n\n## 重点方向\n\n- 完成产品新版本\n- 每周留出半天深度工作\n- 建立稳定的复盘习惯', favorite: false },
    { id: 'product-3', title: '设计系统学习笔记', content: '# 设计系统学习笔记\n\n好的设计系统不是限制创造力，而是让团队把精力用在更重要的地方。', favorite: false }
  ]},
  { id: 'reading', title: '阅读与输入', description: '书籍、文章和值得保留的观点', color: 'blue', updated: '6 月 10 日', notes: [
    { id: 'reading-1', title: '读《置身事内》', content: '# 读《置身事内》\n\n记录一些触动我的章节和观点。\n\n## 一个值得反复想的问题\n\n我们如何共同塑造身处的环境？', favorite: true },
    { id: 'reading-2', title: '待读清单', content: '# 待读清单\n\n- 《纳瓦尔宝典》\n- 《有限与无限的游戏》\n- 《卡片笔记写作法》', favorite: false }
  ]},
  { id: 'life', title: '生活记录', description: '日记、旅行与生活中的小事', color: 'green', updated: '6 月 08 日', notes: [
    { id: 'life-1', title: '周末去看展', content: '# 周末去看展\n\n很久没有留出一整天给自己了。看看展览，走走路，或许会有新的发现。', favorite: false }
  ]}
];

let selectedCollection = collections[0];
let selectedNote = selectedCollection.notes[0];
let filteredCollections = collections;
let currentView = 'collections';
const $ = selector => document.querySelector(selector);
const toast = $('#toast');

function showToast(message) { toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 1800); }
function countNotes() { return collections.reduce((total, collection) => total + collection.notes.length, 0); }
function renderCollections(list = filteredCollections) {
  $('#collections-list').innerHTML = list.map(collection => `<article class="collection-card ${collection.id === selectedCollection.id ? 'selected' : ''}" data-collection="${collection.id}"><div class="collection-card-top"><span class="collection-icon ${collection.color}">◈</span><span class="collection-count">${collection.notes.length} 篇</span></div><div class="collection-title-row"><h2>${collection.title}</h2><div class="collection-actions"><button data-action="rename" title="重命名">✎</button><button data-action="delete" title="删除">×</button></div></div><p>${collection.description || '暂无描述'}</p><div class="collection-notes">${collection.notes.map(note => `<button class="collection-note ${note.id === selectedNote.id ? 'active' : ''}" data-note="${note.id}"><span>${note.favorite ? '★' : '·'}</span>${note.title}<i data-action="delete-note" title="删除笔记">×</i></button>`).join('')}</div><div class="collection-meta"><span>${collection.updated}</span><span class="collection-dots">•••</span></div></article>`).join('');
  $('#collection-count').textContent = collections.length; $('#note-count').textContent = countNotes(); $('#nav-collection-count').textContent = collections.length; $('#nav-note-count').textContent = countNotes();
}
function renderLooseNotes() { const groups = {}; collections.forEach(collection => collection.notes.forEach(note => { const group = collection.title; if (!groups[group]) groups[group] = { collection, notes: [] }; groups[group].notes.push(note); })); $('#collections-list').innerHTML = Object.values(groups).map(group => `<div class="loose-group"><div class="loose-group-title"><span class="collection-icon ${group.collection.color}">◈</span><b>${group.collection.title}</b><small>${group.notes.length} 篇</small></div>${group.notes.map(note => `<button class="loose-note ${note.id === selectedNote.id ? 'active' : ''}" data-note="${note.id}" data-collection="${group.collection.id}"><span>${note.favorite ? '★' : '·'}</span><b>${note.title}</b><small>Markdown 笔记</small></button>`).join('')}</div>`).join(''); }
function switchView(view) { currentView = view; document.querySelectorAll('.main-nav .nav-item').forEach(item => item.classList.remove('active')); $(`#${view}-nav`).classList.add('active'); $('.panel-heading > span').textContent = view === 'collections' ? '我的聚合体' : '笔记列表'; $('#add-note').classList.toggle('hidden', view !== 'collections'); $('#add-collection').classList.toggle('hidden', view !== 'collections'); if (view === 'collections') renderCollections(); else renderLooseNotes(); }
function renderEditor() { $('#editor-title').textContent = selectedNote ? selectedNote.title : '选择一篇笔记'; $('#markdown-editor').value = selectedNote ? selectedNote.content : ''; updatePreview(); updateWordCount(); }
function markdownToHtml(markdown) { const safe = markdown.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); return safe.split('\n').map(line => { if (line.startsWith('### ')) return `<h4>${line.slice(4)}</h4>`; if (line.startsWith('## ')) return `<h3>${line.slice(3)}</h3>`; if (line.startsWith('# ')) return `<h2>${line.slice(2)}</h2>`; if (line.startsWith('- ')) return `<li>${line.slice(2)}</li>`; if (line.startsWith('> ')) return `<blockquote>${line.slice(2)}</blockquote>`; return line ? `<p>${line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>').replace(/\*(.*?)\*/g, '<em>$1</em>')}</p>` : '<div class="md-spacer"></div>'; }).join('').replace(/(<li>.*?<\/li>)+/g, group => `<ul>${group}</ul>`); }
function updatePreview() { $('#markdown-preview').innerHTML = markdownToHtml($('#markdown-editor').value); }
function updateWordCount() { $('#word-count').textContent = `${$('#markdown-editor').value.replace(/\s/g, '').length} 字`; }
function selectCollection(id) { selectedCollection = collections.find(collection => collection.id === id) || collections[0]; selectedNote = selectedCollection.notes[0] || null; renderCollections(); renderEditor(); }
function createNote() { if (!selectedCollection) return; const title = window.prompt('请输入笔记名称', '未命名笔记'); if (!title || !title.trim()) return; const note = { id: `note-${Date.now()}`, title: title.trim(), content: `# ${title.trim()}\n\n在这里开始记录……`, favorite: false }; selectedCollection.notes.push(note); selectedCollection.updated = '刚刚'; selectedNote = note; filteredCollections = collections; renderCollections(); renderEditor(); showToast('笔记已创建'); }
function deleteNote(noteId) { if (selectedCollection.notes.length === 1) { showToast('至少保留一篇笔记'); return; } const index = selectedCollection.notes.findIndex(note => note.id === noteId); if (index < 0) return; selectedCollection.notes.splice(index, 1); selectedNote = selectedCollection.notes[Math.max(0, index - 1)]; renderCollections(); renderEditor(); showToast('笔记已删除'); }
function openModal() { $('#collection-modal').classList.remove('hidden'); $('#collection-form').reset(); $('#collection-form').elements.title.focus(); }
function closeModal() { $('#collection-modal').classList.add('hidden'); }
function createCollection(event) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const id = `collection-${Date.now()}`; const templateCount = Number(data.get('template')); const names = ['概览', '待办事项', '灵感与资料'].slice(0, templateCount); const collection = { id, title: data.get('title').trim(), description: data.get('description').trim(), color: 'purple', updated: '刚刚', notes: names.map((title, index) => ({ id: `${id}-${index}`, title, content: `# ${title}\n\n在这里开始记录……`, favorite: false })) }; collections.unshift(collection); selectedCollection = collection; selectedNote = collection.notes[0] || null; filteredCollections = collections; closeModal(); switchView('collections'); renderEditor(); showToast('聚合体已创建'); }
function renameCollection() { const title = window.prompt('请输入新的聚合体名称', selectedCollection.title); if (!title || !title.trim()) return; selectedCollection.title = title.trim(); selectedCollection.updated = '刚刚'; renderCollections(); showToast('名称已修改'); }
function deleteCollection() { if (collections.length === 1) { showToast('至少保留一个聚合体'); return; } if (!window.confirm(`确定删除“${selectedCollection.title}”及其中的全部笔记吗？`)) return; const index = collections.findIndex(collection => collection.id === selectedCollection.id); collections.splice(index, 1); selectedCollection = collections[Math.max(0, index - 1)]; selectedNote = selectedCollection.notes[0]; filteredCollections = collections; renderCollections(); renderEditor(); showToast('聚合体已删除'); }

$('#collections-list').addEventListener('click', event => { const looseNote = event.target.closest('.loose-note'); if (looseNote) { selectedCollection = collections.find(collection => collection.id === looseNote.dataset.collection); selectedNote = selectedCollection.notes.find(note => note.id === looseNote.dataset.note); renderLooseNotes(); renderEditor(); return; } const noteButton = event.target.closest('.collection-note'); const action = event.target.dataset.action; const card = event.target.closest('.collection-card'); if (!card) return; if (action === 'delete-note') { event.stopPropagation(); deleteNote(noteButton.dataset.note); return; } if (action === 'rename') { event.stopPropagation(); selectCollection(card.dataset.collection); renameCollection(); return; } if (action === 'delete') { event.stopPropagation(); selectCollection(card.dataset.collection); deleteCollection(); return; } if (noteButton) { selectedCollection = collections.find(collection => collection.notes.some(note => note.id === noteButton.dataset.note)); selectedNote = selectedCollection.notes.find(note => note.id === noteButton.dataset.note); renderCollections(); renderEditor(); return; } selectCollection(card.dataset.collection); });
$('#markdown-editor').addEventListener('input', event => { if (!selectedNote) return; selectedNote.content = event.target.value; $('#save-status').textContent = '保存中…'; updatePreview(); updateWordCount(); clearTimeout(window.saveTimer); window.saveTimer = setTimeout(() => { $('#save-status').textContent = '已保存'; }, 500); });
$('#preview-toggle').addEventListener('click', () => { const editor = $('#markdown-editor'); const preview = $('#markdown-preview'); const previewing = !preview.classList.contains('hidden'); preview.classList.toggle('hidden', previewing); editor.classList.toggle('hidden', !previewing); $('#preview-toggle').textContent = previewing ? '预览' : '编辑'; });
$('#search-input').addEventListener('input', event => { const keyword = event.target.value.trim().toLowerCase(); filteredCollections = keyword ? collections.map(collection => ({ ...collection, notes: collection.notes.filter(note => `${collection.title}${collection.description}${note.title}${note.content}`.toLowerCase().includes(keyword)) })).filter(collection => collection.notes.length || `${collection.title}${collection.description}`.toLowerCase().includes(keyword)) : collections; renderCollections(filteredCollections); });
$('#filter-button').addEventListener('click', () => $('#filter-menu').classList.toggle('hidden')); $('#filter-menu').addEventListener('click', event => { const sort = event.target.dataset.sort; if (!sort) return; filteredCollections.sort((a, b) => sort === 'az' ? a.title.localeCompare(b.title, 'zh') : sort === 'oldest' ? b.updated.localeCompare(a.updated) : a.updated.localeCompare(b.updated)); renderCollections(); $('#filter-menu').classList.add('hidden'); });
$('#new-collection').addEventListener('click', openModal); $('#add-collection').addEventListener('click', openModal); $('#collection-form').addEventListener('submit', createCollection); $('#close-modal').addEventListener('click', closeModal); $('#cancel-modal').addEventListener('click', closeModal); $('#collection-modal').addEventListener('click', event => { if (event.target.id === 'collection-modal') closeModal(); }); $('#add-note').addEventListener('click', createNote); $('#collections-nav').addEventListener('click', event => { event.preventDefault(); switchView('collections'); }); $('#notes-nav').addEventListener('click', event => { event.preventDefault(); switchView('notes'); });
document.addEventListener('keydown', event => { if (event.key === 'Escape') closeModal(); if (event.key.toLowerCase() === 'n' && document.activeElement.tagName !== 'INPUT' && document.activeElement.tagName !== 'TEXTAREA') openModal(); if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); $('#search-input').focus(); } });
$('#theme-toggle').addEventListener('click', () => { document.body.classList.toggle('dark'); showToast(document.body.classList.contains('dark') ? '已切换深色模式' : '已切换浅色模式'); });
renderCollections(); renderEditor();
